
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  gstin: 'gstin',
  address: 'address',
  state_code: 'state_code',
  logo_url: 'logo_url',
  financial_year_start: 'financial_year_start',
  billing_mode: 'billing_mode',
  owner_name: 'owner_name',
  invoice_use_branch_name: 'invoice_use_branch_name',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  is_deleted: 'is_deleted'
};

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  address: 'address',
  gstin: 'gstin',
  phone: 'phone',
  is_default: 'is_default',
  bank_name: 'bank_name',
  bank_account_no: 'bank_account_no',
  bank_ifsc: 'bank_ifsc',
  bank_branch: 'bank_branch',
  digital_sign_url: 'digital_sign_url',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  is_deleted: 'is_deleted'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  company_id: 'company_id',
  password: 'password',
  role: 'role',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  is_deleted: 'is_deleted'
};

exports.Prisma.UserBranchAccessScalarFieldEnum = {
  user_id: 'user_id',
  branch_id: 'branch_id'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  branch_id: 'branch_id',
  name: 'name',
  phone: 'phone',
  email: 'email',
  gstin: 'gstin',
  address: 'address',
  state_code: 'state_code',
  credit_limit: 'credit_limit',
  opening_balance: 'opening_balance',
  client_type: 'client_type',
  rate_type: 'rate_type',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  is_deleted: 'is_deleted'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  phone: 'phone',
  email: 'email',
  gstin: 'gstin',
  address: 'address',
  state_code: 'state_code',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  is_deleted: 'is_deleted'
};

exports.Prisma.ItemScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  code: 'code',
  barcode: 'barcode',
  group_id: 'group_id',
  unit_id: 'unit_id',
  hsn_code: 'hsn_code',
  tax_rate: 'tax_rate',
  item_type: 'item_type',
  sale_price_1: 'sale_price_1',
  sale_price_2: 'sale_price_2',
  sale_price_3: 'sale_price_3',
  purchase_price: 'purchase_price',
  mrp: 'mrp',
  min_margin_pct: 'min_margin_pct',
  track_inventory: 'track_inventory',
  track_batches: 'track_batches',
  track_serials: 'track_serials',
  reorder_level: 'reorder_level',
  reorder_qty: 'reorder_qty',
  image_url: 'image_url',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by',
  is_deleted: 'is_deleted'
};

exports.Prisma.ItemGroupScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  parent_id: 'parent_id',
  created_at: 'created_at'
};

exports.Prisma.ItemUnitScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  abbreviation: 'abbreviation',
  created_at: 'created_at'
};

exports.Prisma.ItemVariantScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  size: 'size',
  colour: 'colour',
  barcode: 'barcode',
  price_modifier: 'price_modifier'
};

exports.Prisma.ItemBatchScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  batch_no: 'batch_no',
  mfg_date: 'mfg_date',
  expiry_date: 'expiry_date',
  purchase_price: 'purchase_price'
};

exports.Prisma.ItemSerialScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  batch_id: 'batch_id',
  serial_no: 'serial_no',
  status: 'status'
};

exports.Prisma.PriceSlabScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  min_qty: 'min_qty',
  max_qty: 'max_qty',
  price: 'price'
};

exports.Prisma.ItemVendorCatalogScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  supplier_id: 'supplier_id',
  vendor_item_code: 'vendor_item_code',
  vendor_price: 'vendor_price',
  lead_days: 'lead_days'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  branch_id: 'branch_id',
  type: 'type',
  transaction_no: 'transaction_no',
  date: 'date',
  party_id: 'party_id',
  party_name: 'party_name',
  subtotal: 'subtotal',
  discount: 'discount',
  tax_amount: 'tax_amount',
  total: 'total',
  amount_paid: 'amount_paid',
  status: 'status',
  notes: 'notes',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by'
};

exports.Prisma.TransactionItemScalarFieldEnum = {
  id: 'id',
  transaction_id: 'transaction_id',
  item_id: 'item_id',
  item_name: 'item_name',
  quantity: 'quantity',
  rate: 'rate',
  discount: 'discount',
  tax_rate: 'tax_rate',
  tax_amount: 'tax_amount',
  total: 'total'
};

exports.Prisma.TransactionTaxScalarFieldEnum = {
  id: 'id',
  transaction_id: 'transaction_id',
  tax_name: 'tax_name',
  rate: 'rate',
  taxable_amount: 'taxable_amount',
  tax_amount: 'tax_amount'
};

exports.Prisma.TransactionPaymentScalarFieldEnum = {
  id: 'id',
  transaction_id: 'transaction_id',
  mode: 'mode',
  amount: 'amount',
  ref_no: 'ref_no',
  bank_id: 'bank_id',
  cheque_date: 'cheque_date'
};

exports.Prisma.StockLedgerScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  branch_id: 'branch_id',
  item_id: 'item_id',
  transaction_id: 'transaction_id',
  type: 'type',
  quantity: 'quantity',
  remarks: 'remarks',
  date: 'date',
  created_at: 'created_at',
  created_by: 'created_by'
};

exports.Prisma.LocationTransferScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  from_branch_id: 'from_branch_id',
  to_branch_id: 'to_branch_id',
  status: 'status',
  transfer_no: 'transfer_no',
  date: 'date',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by: 'created_by'
};

exports.Prisma.TransferItemScalarFieldEnum = {
  id: 'id',
  transfer_id: 'transfer_id',
  item_id: 'item_id',
  quantity: 'quantity'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  type: 'type',
  code: 'code',
  created_at: 'created_at'
};

exports.Prisma.JournalEntryScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  branch_id: 'branch_id',
  date: 'date',
  reference: 'reference',
  narration: 'narration',
  created_at: 'created_at',
  created_by: 'created_by'
};

exports.Prisma.JournalEntryLineScalarFieldEnum = {
  id: 'id',
  journal_entry_id: 'journal_entry_id',
  account_id: 'account_id',
  debit: 'debit',
  credit: 'credit'
};

exports.Prisma.ShiftScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  branch_id: 'branch_id',
  user_id: 'user_id',
  start_time: 'start_time',
  end_time: 'end_time',
  opening_cash: 'opening_cash',
  closing_cash: 'closing_cash',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.AttendanceScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  branch_id: 'branch_id',
  user_id: 'user_id',
  date: 'date',
  clock_in: 'clock_in',
  clock_out: 'clock_out',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.PayrollScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  user_id: 'user_id',
  month: 'month',
  year: 'year',
  basic_salary: 'basic_salary',
  allowances: 'allowances',
  deductions: 'deductions',
  net_payable: 'net_payable',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.LoyaltyRewardScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  client_id: 'client_id',
  points: 'points',
  tier: 'tier',
  points_earned: 'points_earned',
  points_spent: 'points_spent',
  balance: 'balance',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.DiscountSchemeScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  type: 'type',
  discount_value: 'discount_value',
  is_percentage: 'is_percentage',
  min_bill_value: 'min_bill_value',
  start_date: 'start_date',
  end_date: 'end_date',
  is_active: 'is_active',
  is_deleted: 'is_deleted',
  created_by: 'created_by',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ClientProductPriceScalarFieldEnum = {
  id: 'id',
  client_id: 'client_id',
  item_id: 'item_id',
  price: 'price'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Company: 'Company',
  Branch: 'Branch',
  User: 'User',
  UserBranchAccess: 'UserBranchAccess',
  Client: 'Client',
  Supplier: 'Supplier',
  Item: 'Item',
  ItemGroup: 'ItemGroup',
  ItemUnit: 'ItemUnit',
  ItemVariant: 'ItemVariant',
  ItemBatch: 'ItemBatch',
  ItemSerial: 'ItemSerial',
  PriceSlab: 'PriceSlab',
  ItemVendorCatalog: 'ItemVendorCatalog',
  Transaction: 'Transaction',
  TransactionItem: 'TransactionItem',
  TransactionTax: 'TransactionTax',
  TransactionPayment: 'TransactionPayment',
  StockLedger: 'StockLedger',
  LocationTransfer: 'LocationTransfer',
  TransferItem: 'TransferItem',
  Account: 'Account',
  JournalEntry: 'JournalEntry',
  JournalEntryLine: 'JournalEntryLine',
  Shift: 'Shift',
  Attendance: 'Attendance',
  Payroll: 'Payroll',
  LoyaltyReward: 'LoyaltyReward',
  DiscountScheme: 'DiscountScheme',
  ClientProductPrice: 'ClientProductPrice'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
